# ── Etapa 1: Compilação ──────────────────────────────────────
FROM golang:1.21-alpine AS builder

WORKDIR /src
COPY go.mod ./
COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/drone ./drone/

# ── Etapa 2: Imagem final ─────────────────────────────────────
FROM alpine:3.19

WORKDIR /app

COPY --from=builder /out/drone .

# Certificados TLS para conectar ao broker via TLS
COPY cert.pem .
COPY key.pem  .

ENV CONFIG_PATH=/app/config.json

# Argumentos: [ID_DRONE] [ENDERECO_PROPRIO] [ENDERECO_BROKER]
# Exemplo:    drone1 drone1:9091 broker1:9081
ENTRYPOINT ["/app/drone"]
